version: "3"
services:
  nginx:
    container_name: symfony_hw_7
    build:
      context: .
      dockerfile: deploy/nginx/Dockerfile
    volumes:
      - ./deploy/nginx/templates:/etc/nginx/templates
      - ./symfony_hw_7:/data/symfony_hw_7
    ports:
      - "8081:80"
    environment:
      - NGINX_CUSTOM_SERVER_NAME=project-2021.local
      - NGINX_SYMFONY_SERVER_NAME=project-symfony.local

  php:
    container_name: project-php3
    build:
      context: .
      dockerfile: deploy/php-fpm/Dockerfile
    volumes:
      - ./symfony_hw_7:/data/symfony_hw_7
