version: "3"
services:
  nginx:
    container_name: my_symfony_project
    build:
      context: .
      dockerfile: deploy/nginx/Dockerfile
    volumes:
      - ./deploy/nginx/templates:/etc/nginx/templates
      - ./my_symfony_project:/data/my_symfony_project
    ports:
      - "8081:80"
    environment:
      - NGINX_CUSTOM_SERVER_NAME=project-2021.local
      - NGINX_SYMFONY_SERVER_NAME=project-symfony.local

  php:
    container_name: project-php45
    build:
      context: .
      dockerfile: deploy/php-fpm/Dockerfile
    volumes:
      - ./my_symfony_project:/data/my_symfony_project
